import { describe, expect, it } from 'vitest';
import { difficultyFor, difficultyScore, RecommendationService, seededRng } from './recommendation.js';
import type { Champion, ChampionDataProvider, ChampionStats, ChampionStatsProvider, MatchupStats, Position } from '../domain.js';
const champions: Champion[] = [
  { id: 'easy', name: '쉬움', imageUrl: '', positions: ['미드'], difficultyFactors: { skillShot: 1, mechanics: 1, laning: 1, survival: 2, scaling: 2, decisionMaking: 2 } },
  { id: 'mid', name: '보통', imageUrl: '', positions: ['미드'], difficultyFactors: { skillShot: 2, mechanics: 2, laning: 2, survival: 2, scaling: 2, decisionMaking: 2 } },
  { id: 'hard', name: '어려움', imageUrl: '', positions: ['미드'], difficultyFactors: { skillShot: 3, mechanics: 3, laning: 3, survival: 3, scaling: 3, decisionMaking: 3 } },
];
const stats: ChampionStats[] = champions.map((champion, index) => ({ championId: champion.id, position: '미드', winRate: .50 + index / 100, pickRate: .03 + index / 100, games: index === 0 ? 100 : 10000, patch: 'demo', tier: 'all', region: 'KR', isSample: true, reason: '' }));
const matchups: MatchupStats[] = [{ championId: 'easy', opponentId: 'hard', position: '미드', winRate: .45, opponentPickRate: .1, games: 5000, patch: 'demo', tier: 'all' }, { championId: 'easy', opponentId: 'mid', position: '미드', winRate: .47, opponentPickRate: .08, games: 4000, patch: 'demo', tier: 'all' }];
const data: ChampionDataProvider = { getChampions: async () => champions, getChampionById: async (id) => champions.find((item) => item.id === id) ?? null }; const provider: ChampionStatsProvider = { getStats: async (position: Position) => stats.filter((item) => item.position === position), getMatchups: async () => matchups };
describe('recommendation', () => { it('calculates difficulty boundaries', () => { expect(difficultyScore(champions[0].difficultyFactors)).toBeCloseTo(1.5); expect(difficultyFor(champions[0].difficultyFactors)).toBe('쉬움'); expect(difficultyFor(champions[1].difficultyFactors)).toBe('보통'); expect(difficultyFor(champions[2].difficultyFactors)).toBe('어려움'); }); it('filters candidates and is reproducible', async () => { const one = new RecommendationService(data, provider, seededRng(7)); const two = new RecommendationService(data, provider, seededRng(7)); expect((await one.recommend('미드', '쉬움', 4)).map((item) => item.champion.id)).toEqual(['easy']); expect((await one.recommend('미드', '보통', 4)).map((item) => item.champion.id)).toEqual((await two.recommend('미드', '보통', 4)).map((item) => item.champion.id)); }); it('returns unique same-position ban candidates ordered by disadvantage', async () => { const result = await new RecommendationService(data, provider).banRecommendations('easy', '미드'); expect(result).toHaveLength(2); expect(new Set(result.map((item) => item.champion.id)).size).toBe(2); expect(result[0].champion.id).toBe('hard'); }); });
