import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, StringSelectMenuBuilder, type ButtonInteraction, type ChatInputCommandInteraction, type Client, type StringSelectMenuInteraction } from 'discord.js';
import { difficulties, positions, type Difficulty, type Position } from './domain.js';
import { RecommendationService } from './services/recommendation.js';
import { MemorySessionStore } from './services/session.js';

const componentId = (id: string, action: string, value = '') => `${id}:${action}:${value}`;
const positionMenu = (sessionId: string) => new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(componentId(sessionId, 'position')).setPlaceholder('포지션을 선택하세요').addOptions(positions.map((value) => ({ label: value, value }))));
const difficultyMenu = (sessionId: string) => new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(componentId(sessionId, 'difficulty')).setPlaceholder('난이도를 선택하세요').addOptions(difficulties.map((value) => ({ label: value, value }))));

export class DiscordRecommendationController {
  constructor(private readonly service: RecommendationService, private readonly sessions: MemorySessionStore) {}
  async start(interaction: ChatInputCommandInteraction): Promise<void> { const session = this.sessions.create({ userId: interaction.user.id, guildId: interaction.guildId ?? undefined, channelId: interaction.channelId, recommendedChampionIds: [] }); await interaction.reply({ content: '롤챔봇입니다. 플레이할 포지션을 선택해 주세요.', components: [positionMenu(session.id)], ephemeral: false }); }
  async handle(interaction: ButtonInteraction | StringSelectMenuInteraction): Promise<void> {
    const [sessionId, action, value] = interaction.customId.split(':'); const session = this.sessions.get(sessionId);
    if (!session) { await interaction.reply({ content: '이 추천 세션은 만료되었습니다. `/챔피언추천`으로 다시 시작해 주세요.', ephemeral: true }); return; }
    if (session.userId !== interaction.user.id) { await interaction.reply({ content: '이 추천은 명령어를 실행한 사용자만 조작할 수 있습니다.', ephemeral: true }); return; }
    const selected = interaction.isStringSelectMenu() ? interaction.values[0] : value;
    if (action === 'position') { this.sessions.update(sessionId, { selectedPosition: selected as Position }); await interaction.update({ content: `${selected} 포지션을 선택했습니다. 난이도를 선택해 주세요.`, embeds: [], components: [difficultyMenu(sessionId)] }); return; }
    if (action === 'difficulty') { await this.showRecommendations(interaction, sessionId, selected as Difficulty); return; }
    if (action === 'champion') { await this.showBans(interaction, sessionId, selected); return; }
    if (action === 'retry') { await this.showRecommendations(interaction, sessionId, session.selectedDifficulty!); return; }
    if (action === 'difficulty-back') { await interaction.update({ content: '난이도를 다시 선택해 주세요.', embeds: [], components: [difficultyMenu(sessionId)] }); return; }
    if (action === 'position-back') { await interaction.update({ content: '포지션을 다시 선택해 주세요.', embeds: [], components: [positionMenu(sessionId)] }); return; }
    await interaction.update({ content: '추천을 종료했습니다. `/챔피언추천`으로 새 추천을 시작할 수 있습니다.', embeds: [], components: [] });
  }
  private async showRecommendations(interaction: ButtonInteraction | StringSelectMenuInteraction, sessionId: string, difficulty: Difficulty): Promise<void> { const session = this.sessions.get(sessionId)!; const results = await this.service.recommend(session.selectedPosition!, difficulty); this.sessions.update(sessionId, { selectedDifficulty: difficulty, recommendedChampionIds: results.map((result) => result.champion.id) }); if (!results.length) { await interaction.update({ content: '현재 이 조건의 데모 데이터가 없습니다. 다른 조건을 선택해 주세요.', components: [difficultyMenu(sessionId)] }); return; } const embed = new EmbedBuilder().setColor(0x5865f2).setTitle(`${session.selectedPosition} · ${difficulty} 추천`).setDescription('데모 데이터 · 샘플 통계이며 실제 경쟁전 데이터와 다를 수 있습니다.').setImage(results[0].champion.imageUrl).addFields(results.map((result, index) => ({ name: `${index + 1}. ${result.champion.name} · ${difficulty}`, value: `승률 **${(result.stats.winRate * 100).toFixed(1)}%** · 픽률 **${(result.stats.pickRate * 100).toFixed(1)}%** · ${result.stats.games.toLocaleString()}경기\n${result.stats.reason}\n${result.stats.patch} · ${result.stats.tier} · ${result.stats.region}`, inline: false }))); const choices = new ActionRowBuilder<ButtonBuilder>().addComponents(results.map((result, index) => new ButtonBuilder().setCustomId(componentId(sessionId, 'champion', result.champion.id)).setLabel(`${index + 1}. ${result.champion.name}`).setStyle(ButtonStyle.Primary))); const navigation = new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(componentId(sessionId, 'retry')).setLabel('같은 조건으로 다시 추천').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(componentId(sessionId, 'difficulty-back')).setLabel('다른 난이도 선택').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(componentId(sessionId, 'position-back')).setLabel('다른 포지션 선택').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(componentId(sessionId, 'end')).setLabel('종료').setStyle(ButtonStyle.Danger)); await interaction.update({ content: '추천 챔피언을 하나 선택하면 밴 후보를 알려드릴게요.', embeds: [embed], components: [choices, navigation] }); }
  private async showBans(interaction: ButtonInteraction | StringSelectMenuInteraction, sessionId: string, championId: string): Promise<void> { const session = this.sessions.get(sessionId)!; this.sessions.update(sessionId, { selectedChampionId: championId }); const bans = await this.service.banRecommendations(championId, session.selectedPosition!); const champion = (await this.service.getChampion(championId))!; const embed = new EmbedBuilder().setColor(0xed4245).setTitle(`${champion.name} 밴 추천 · ${session.selectedPosition}`).setDescription('데모 데이터 · 승률의 주체는 선택한 챔피언입니다.').setImage(bans[0]?.champion.imageUrl ?? champion.imageUrl).addFields(bans.map((ban, index) => ({ name: `${index + 1}. ${ban.champion.name}`, value: `${champion.name}의 ${ban.champion.name} 상대 승률: **${(ban.matchup.winRate * 100).toFixed(1)}%**\n상대 픽률 ${(ban.matchup.opponentPickRate * 100).toFixed(1)}% · ${ban.matchup.games.toLocaleString()}경기\n불리한 매치업이면서 실제 등장 빈도도 높은 후보입니다.\n${ban.matchup.patch} · ${ban.matchup.tier}`, inline: false }))).setFooter({ text: bans.length ? '동일 포지션 매치업만 사용했습니다.' : '해당 챔피언의 밴 데모 데이터가 없습니다.' }); const navigation = new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(componentId(sessionId, 'retry')).setLabel('같은 조건으로 다시 추천').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(componentId(sessionId, 'difficulty-back')).setLabel('다른 난이도 선택').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(componentId(sessionId, 'position-back')).setLabel('다른 포지션 선택').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(componentId(sessionId, 'end')).setLabel('종료').setStyle(ButtonStyle.Danger)); await interaction.update({ content: '밴 추천 결과입니다.', embeds: [embed], components: [navigation] }); }
}
export function wireBot(client: Client, controller: DiscordRecommendationController): void { client.on('interactionCreate', async (interaction) => { try { if (interaction.isChatInputCommand() && interaction.commandName === '챔피언추천') await controller.start(interaction); else if (interaction.isButton() || interaction.isStringSelectMenu()) await controller.handle(interaction); } catch (error) { console.error(error); if (interaction.isRepliable() && !interaction.replied && !interaction.deferred) await interaction.reply({ content: '처리 중 오류가 발생했습니다.', ephemeral: true }); } }); }
